version: '3.9'

services:
  db:
    image: 'mongo'
    container_name: MONGODB_POKEDEX
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/data/db

  api:
    container_name: POKEDEX_BACKEND
    build: '.'
    volumes:
      - ./:/pokemon-app
      - ./node_modules:/pokemon-app/node_modules
    environment:
      NODE_ENV: development
    depends_on:
      - db
    links:
      - db
    ports:
      - '3000:3000'

  mongo-seed:
    build: ./mongo-seed
    depends_on:
      - db
    
